### ISSUE TITLE
 Error 1

### ISSUE THREAD

**Issue by BitaoQiu** [spficklin/RMTGeneNet#1]
When I tried to compile the file, it shows:

gcc -m64 -c -g RandomMatrix.v2-3.c
RandomMatrix.v2-3.c:20:17: fatal error: mkl.h: No such file or directory
compilation terminated.
make: **\* [RandomMatrix.v2-3.o] Error 1

May I ask how to solve this?

**Comment by spficklin** [comment]
Hi StanQiu,

Currently the code uses the Intel Kernel Math library to handle eigenvalue calculations.  This library provides the mkl.h file you are missing.   I believe you can obtain these libraries for free from here: http://software.intel.com/en-us/non-commercial-software-development.  Let us know if this solves your problem.

**Comment by BitaoQiu** [comment]
Hi, thanks for the advise, it works well.

Stan Qiu
