### ISSUE TITLE
Error on ccm execution

### ISSUE THREAD

**Issue by nlazza** [spficklin/RMTGeneNet#2]
When I try to execute the ccm command I get this error:
Segmentation fault (core dumped)

Any idea?

**Comment by smgibso** [comment]
This error could come from a variety of sources, but most commonly from issues reading in the input data file. Could you please double check the file formatting, input sizes (rows and columns of data), and provide more information on your running parameters?

Thanks

**Comment by nlazza** [comment]
I discovered it was a problem of compilation, so I exported the C_PATH and the LD_PATH in order to find the right libraries e and header files. Now the execution of ccm works well, while the execution of rmm doesn't work at all, it seems that it runs doing nothing, no threshold appear as output. The input file is a very simple random matrix:
a   0.35    0.46    0.66    0.33
b   0.10    0.25    0.31    0.24
c   0.12    0.55    0.66    0.22
d   0.11    1.56    1.31    0.33
f   0.12    0.14    1.00    1.25
