### ISSUE TITLE
Correlation matrix input

### ISSUE THREAD

**Issue by aleccrowell** [spficklin/RMTGeneNet#3]
Is there any way to feed RMTGeneNet an arbitrary correlation matrix (i.e. Spearman, HIS etc)?

**Comment by spficklin** [comment]
Not currently, however, it may be something we can accommodate.  What format is your matrix in?

**Comment by spficklin** [comment]
There has been no response on this issue, so marking as closed.  Although the most recent version now supports Spearman and Mutual Information.
