### ISSUE TITLE
How to calculate thresholds for correlation estimations besides Pearson

### ISSUE THREAD

**Issue by jmwhitha** [spficklin/RMTGeneNet#6]
I'd like to use the DEGNserver (http://plantgrn.noble.org/DeGNServer/Analysis.jsp) to perform network analyses using all of their available correlation estimation methods: Pearson, Spearman, Kendall, Mutual Information, Maximal Information, and Thei-Sen. Before I can do this, I would like to calculate an appropriate threshold using RMTGeneNet for each of these estimation methods. I have only found instructions for the Pearson method.

Can you please provide a detailed step by step protocol for running linux commands that will help me achieve this end?

Thank you,
Jason

**Comment by spficklin** [comment]
Hi Jason,

Unfortunately, the way that RMTGeneNet is designed it uses a binary format for the correlation matrix. The binary files are created using the "similarity" step (prior to thresholding), and RMTGeneNet only supports Pearson, Spearman and Mutual Information (not the others you mention).  So, the only way to get RMTGeneNet to perform RMT thresholding is if your correlation matrix is in that binary format. I may be able to expand the program to support conversion of an input file into the binary format so you can run the threshold.  What format is your correlation matrix?

Stephen

**Comment by jmwhitha** [comment]
Hi Stephen,

So your procedure if I'm understanding is:
1) Perform network analysis with say Spearman with an initial threshold of 0.8 
2) Convert the resulting coexpression file with gene1, gene2, and CE columns into a binary (how do I do that?)
3) Run rmm
Does ccm find just correlations above a initial threshold or all correlations between all genes? 

The output for DEGNserver for all methods is a **tab delimited file with Gene1, Gene2, and CE** (for all the correlations above the threshold) as columns 1, 2, and 3. It's great. You should try to connect with them because it would be easy to make your method an add-on and get lots of citations.

Thank you,
Jason

PS- I also continued on the thread you started 7 days ago called "Segfault on example data (CentOS) #5"

**Comment by spficklin** [comment]
The typical procedure would be:

1) Construct the correlation matrix by running the 'ccm' program first.   There is no threshold for this step, and you can choose Spearman, Pearson or Mutual Information.
2)  Threshold the correlation matrix using the 'rmm' command.   It reads the binary files created in step 1.
3) Use the perl script to extract the network after rmm gives you the network.

BTW.... we will be releasing an improved version of the code this summer that should make generation of networks much easier.   It's currently in a private repository.

It sounds like DEGNserver is already providing you with a network that has been thresholded.  Is there a reason you want to apply RMT thresholding again?   

If you have the unthresholded correlation file and you really want to use RMT we can perhaps adjust RMTGeneNet to allow that but it would be ideal to have the unthresholded version.

**Comment by jmwhitha** [comment]
Yes, I followed the typical procedure. Sorry I wasn't clear. The procedure I mentioned above would be my understanding of your proposed alternative for a new input method.

That's great but I'm anxious to use your method now if possible.

The reason why I would like to use your method is because I am arbitrarily picking a threshold for DEGNserver. I am having trouble with the current software. Perhaps we could just start with getting the Pearson, Spearman and Kendall thresholds calculated. I have a tab delimited text file with 195 columns not including the first one with locus tags and 3176 rows not including the header. I tried ccm as instructed in the README and it only gives me a pc0.bin, no pc1.bin as with the yeast example file. As I mentioned on the other string issue, there was a problem with rmm with the output of ccm yeast example.

**Comment by spficklin** [comment]
Oh, I see. Yes, I was a bit confused...  

The number of .bin files is dependent on the number of rows you have in your input expression matrix. So it's not a big deal if the pc1.bin is missing. With only 3,176 rows in your expression matrix it's not needed.  

After running 'ccm' did you run 'rmm' in the same directory where you ran 'ccm'?  Is 'rmm' not working for your dataset?   Also, how were these 3,176 rows selected?  Are they from a differential expression analysis or were they selected from a previous run of the DEGNserver?

**Comment by spficklin** [comment]
BTW... I'll be out of the office for the next few days so I may not be able to respond to further comments until next week.

**Comment by jmwhitha** [comment]
rmm didn't work for the example or my dataset. Please see the other "issue" string for the details.

The matrix is normalized expression data. Columns of arrays and rows of genes.

Oh no! Could you please take a look at the other string and see if you could get me going with the make file and/ or MLK before you leave?

**Comment by spficklin** [comment]
I believe the issues raised here have been resolved with the most recent development version.  So, I'm marking this as closed.   If there are still issues please reopen.
