### ISSUE TITLE
Segmentation Fault and Flag Errors with new release

### ISSUE THREAD

**Issue by jmwhitha** [spficklin/RMTGeneNet#7]
Thank you for releasing the new version of RMTGeneNet. The Spearman option is great. However, I am still getting a segmentation fault.

./rmtgnet threshold -e SUPPLEMENTALTABLE_SelectArrays_ALL_RMAnorm_RMTGeneNetInput.txt --rows 3176 --cols 181 --method 'sc'
[lines removed for brevity]
testing threshold: 0.789003...
  Genes: 3176, Num lines per file: 3176
  found matrix of size n x n, n = 1685...
  calculating eigenvalues...
  testing similarity of NNSD with Poisson...
  chi = 170.877590

  testing threshold: 0.788003...
  Genes: 3176, Num lines per file: 3176
  found matrix of size n x n, n = 1699...
  calculating eigenvalues...
  testing similarity of NNSD with Poisson...
  chi = 180.018717

  testing threshold: 0.787003...
  Genes: 3176, Num lines per file: 3176
  found matrix of size n x n, n = 1712...
  calculating eigenvalues...
  testing similarity of NNSD with Poisson...
  chi = 201.272706
Done.
Segmentation fault

 To reduce the number of calculations, I tried using the flags -t for start threshold and -s for step size. It seems like these both seg fault near the same place. The chi values are always greater than 200. Is the program suppose to seg fault, or should it have some output at that point?

God bless and thank you for all your help,
Jason

**Comment by spficklin** [comment]
I just committed a fix to the code that should resolve this for you. If you retrieve the most recent development code and re-run I believe the segfault will no longer be there.  

However, the segfault occurred during the final cleanup phase as the program closes and judging from the output you provide it looks like it finished as it should have.  There should be a file with a sc.th.txt extension that has the desired threshold.

I'm marking this issue as closed but if for some reason this isn't fixed please feel free to reopen.
