### ISSUE TITLE
How to use a binary file of a correlation matrix as input?

### ISSUE THREAD

**Issue by jambqc** [spficklin/RMTGeneNet#8]
This issue is related to the issue titled "Tab delimited correlation matrix as input?" I am needing a similar functionality for my application. Namely, I would like to be able to use other similarity metrics besides Pearson, Spearman, and M.I.  for my applications of the RMT algorithm.

 I know in the previously stated issue that you said the software only supports the binary format. So, my question is how can I use my own binary file in this software? 

Suppose I have a tab-delimited correlation matrix called, 'corr_mat.tsv' that I would like to perform the RMT algorithm on. What steps would I need to take in order to convert this matrix to a binary file which would allow me to use RMTGeneNet software?

**Comment by spficklin** [comment]
Hello.  What format is your corr_mat.tsv file?  I have some R code that may be useful to you if you're just interested in performing RMT thresholding.

**Comment by jambqc** [comment]
Hi,

The corr_mat.tsv file would be tab-separated.
That would be great if you had some R code that would perform the thresholding!

**Comment by spficklin** [comment]
Sorry, I should have been more specific.  What is the structure of your corr_mat.tsv file?  Is it nxn where n is the number of components (i.e. transcripts/genes/probesets)?

**Comment by jambqc** [comment]
Oh yes, sorry, the file would be an N by N symmetric matrix where N is the number of components.

**Comment by spficklin** [comment]
If you can reformat your corr_mat.tsv file into an edge list (e.g. 3 columns:  gene1, gene2, simlarity score) then you can use the [KINC.R](https://github.com/SystemsGenetics/KINC.R) package to find the threshold.   You don't have to include all of your matrix.  For example, to test for a threshold up to a  0.5 you only need to include those components with an absolute similarity score between 0.5 and 1.  (assuming your correlation score is between -1 and 1)

Follow the installation instructions on the home page and then load the KINC.R library. You can get information for how to run the RMT() function by entering "?RMT" on the console.   The R code doesn't specifically give you the threshold.  The code was meant to create plots of the Nearest Neighbor Spacing Distribution as it transitions from Poisson to Guassian.   It's a debugging tool.  But, you can use it for finding a threshold.   The RMTGeneNet code picks the threshold at the point where the Chi-Square value is last seen below 100.    When you run this RMT() code in R it will print out the Chi-Square values but won't stop.  Let it run for a while even after the Chi-square values go above 100.  If you see it get to 200 then you know it won't go back down and you can look at the threshold where it was last below 100 and that will be your final threshold.  

KINC is the future successor to RMTGeneNet. It's a C++ package that is under development and isn't quite ready for prime-time use.  So, I don't recommend trying it out just yet.  We'll be publishing it shortly.  But hopefully the KINC.R project which provides some supplementary R code will help get things moving for you.

The KINC.R package has never been used by anyone else except by our developers.  It's not been 100% tested but I've used it for a few projects and it seems to work for me.   If you encounter problems or have questions please feel free to post an issue to that project

**Comment by jambqc** [comment]
Awesome, thank you very much! I have been working with it this morning and it seems to be doing just what I wanted. Plus, the plots that the RMT function creates of the NNSD are really nice visuals to see what is happening as it transitions.

I really appreciate your help with this.

**Comment by spficklin** [comment]
Great!  Let me know if you have issues with it.
